const { faker } = require('@faker-js/faker');
const db = require('../config/connection');
const Shoe = require('../models/Shoe');

db.once('open', async () => {
  try {
    await Shoe.deleteMany({});

    for (let i = 0; i < 100; i++) {
      await Shoe.create({
        model: faker.commerce.productName(),
        colour: faker.color.human(),
        image: faker.image.sports(
          (width = 250),
          (height = 250),
          (randomize = true)
        ),
        size: faker.helpers.arrayElement([
          '3',
          '3.5',
          '4',
          '4.5',
          '5',
          '5.5',
          '6',
          '6.5',
          '7',
          '7.5',
          '8',
          '8.5',
          '9',
          '9.5',
          '10',
          '10.5',
          '11',
          '11.5',
          '12',
          '12.5',
          '13',
        ]),
        gender: faker.helpers.arrayElement(['F', 'M']),
        price: faker.commerce.price(10, 500, 2),
        featured: faker.helpers.arrayElement([
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ]),
        latest: faker.helpers.arrayElement([
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ]),
        deal: faker.helpers.arrayElement([
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ]),
      });
    }

    console.log('DB seeded');
    process.exit(0);
  } catch (err) {
    throw new Error(err.message);
  }
});
